### ISSUE TITLE
4 Лаба Отчет

### ISSUE THREAD

**Issue by oleg-tgn** [MegaProger228/Kravtsov_Labs#6]
1) Отступы в начале строки то есть то нет

2) Шрифты заголовков прыгают

3) Блок-схема в оригинале может быть хорошая, но в OpenOffice вообще не отображается

4) `В результате выполнения лабораторной №4 были освоены методы работы с двоичными файлами, такие как открытие, запись, закрытие.`

Покажите пожалуйста мне строчку где это вы тут с двоичными файлами работали?

**Comment by MegaProger228** [comment]
Ошибки исправил. Закрываю issues.
